###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/16/2024
#  @package      :  Kitchen Label Printer
#  @description  :  Logic for handling the label printer in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen_label_printer'

shell_command:
  print_kitchen_label: "/bin/bash /config/shell_command/print_kitchen_label.sh '{{content}}' '{{copies}}'"
  print_tape_label: "/bin/bash /config/shell_command/print_tape_label.sh '{{content}}' '{{copies}}'"
  print_office_label: "/bin/bash /config/shell_command/print_office_label.sh '{{content}}' '{{copies}}'"

automation:
  - id: c4fdcb6b-1b34-4445-950e-122605812a25
    alias: Print Kitchen Label
    triggers:
      - trigger: state
        entity_id: input_button.print_main_label
    actions:
      - action: shell_command.print_kitchen_label
        data:
          content: >
            {{ states('input_text.label_text_first') }}
            {%- if states('input_text.label_text_second') != "" -%}
              \n{{ states('input_text.label_text_second') }}
            {%- endif -%}
            {%- if states('input_text.label_text_third') != "" -%}
              \n{{ states('input_text.label_text_third') }}
            {%- endif -%}
            {%- if is_state('input_boolean.print_date', 'on') -%}
              \n{{ states('input_datetime.label_date') }}
            {%- endif -%}
          copies: "{{ states('input_number.label_copies') | round(0) }}"

  - id: cc513eb7-2912-440d-baa9-9d4fd9fd056d
    alias: Print Office Tape Label
    triggers:
      - trigger: state
        entity_id: input_button.print_tape_label
    actions:
      - action: shell_command.print_tape_label
        data:
          content: >
            {{ states('input_text.label_text_first') }}
            {%- if states('input_text.label_text_second') != "" -%}
              \n{{ states('input_text.label_text_second') }}
            {%- endif -%}
            {%- if states('input_text.label_text_third') != "" -%}
              \n{{ states('input_text.label_text_third') }}
            {%- endif -%}
            {%- if is_state('input_boolean.print_date', 'on') -%}
              \n{{ states('input_datetime.label_date') }}
            {%- endif -%}
          copies: "{{ states('input_number.label_copies') | round(0) }}"

  - id: 925e45b5-affc-46cd-921d-227d7777306e
    alias: Print Office Main Label
    triggers:
      - trigger: state
        entity_id: input_button.print_office_label
    actions:
      - action: shell_command.print_office_label
        data:
          content: >
            {{ states('input_text.label_text_first') }}
            {%- if states('input_text.label_text_second') != "" -%}
              \n{{ states('input_text.label_text_second') }}
            {%- endif -%}
            {%- if states('input_text.label_text_third') != "" -%}
              \n{{ states('input_text.label_text_third') }}
            {%- endif -%}
            {%- if is_state('input_boolean.print_date', 'on') -%}
              \n{{ states('input_datetime.label_date') }}
            {%- endif -%}
          copies: "{{ states('input_number.label_copies') | round(0) }}"

  - id: 828c11ac-62c2-49da-891c-7d6b99cd88c4
    alias: Set Label Date to Today at Midnight
    triggers:
      - trigger: time
        at: "00:00:00"
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.label_date
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
