###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen_lights'

      kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
        - ff2b9426281125e3833ee5edf69f5ab0
        - 8d17beb93c0922a46bc4ea30137e4b46

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: group
    name: Kitchen Motion
    unique_id: 8b4d1f31-f15c-47b6-916e-afc97df757d3
    device_class: occupancy
    entities:
      - binary_sensor.kitchen_motion_sensor_motion
      - binary_sensor.kitchen_lights_load_switch_area1occupancy
      - binary_sensor.kitchen_lights_aux_switch_area1occupancy

  - platform: group
    name: Kitchen Sink Occupancy
    unique_id: 252456a9-ef1c-4b28-aa65-d92a71653a8b
    device_class: occupancy
    entities:
      - binary_sensor.kitchen_lights_load_switch_area2occupancy
      - binary_sensor.kitchen_lights_aux_switch_area2occupancy

################################################
## Light
################################################
light:
  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Script
################################################
script:
  update_dishwasher_display:
    use_blueprint:
      path: rohankapoorcom/update-dishwasher-epaper-display.yaml
      input:
        epaper_tag: a3f2009d29c8d2526fb0ad4c94097c63

################################################
## Automation
################################################
automation:
  - id: 6eb0e509-5d18-401a-87e1-d05a7b3854f6
    alias: Update Dishwasher Display
    description: "Set Dishwasher Display status based on power usage"
    use_blueprint:
      path: >-
        sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        power_sensor: sensor.energy_monitor_2_dishwasher_power
        starting_threshold: 25
        finishing_threshold: 15
        actions:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        starting_hysteresis: 5
        finishing_hysteresis: 10
        pre_actions:
          - action: script.update_dishwasher_display
            data:
              state: Running

  - id: 035831df-c284-4935-93fd-a337e2890b8c
    alias: Dishwasher Display Button Triggers
    description: Change the dishwasher display based on buttons triggered
    use_blueprint:
      path: rohankapoorcom/solum-m3-epaper-tag-buttons.yaml
      input:
        epaper_tag:
          - a3f2009d29c8d2526fb0ad4c94097c63
        button_1:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        button_2:
          - action: script.update_dishwasher_display
            data:
              state: Dirty

  - id: 3c66912f-0aa1-469f-9b91-93bfa7c2711f
    alias: Kitchen Light Switch Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch: *kitchen_light_switch_device_ids
        config_button:
          - parallel:
              - action: cover.toggle
                target:
                  entity_id: cover.kitchen_shades
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 170
                  level: 50
                  effect: Open/Close
                  duration: 20 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_a2:
          - parallel:
              - action: light.turn_on
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  brightness_pct: 100
                  kelvin: 3000
                  transition: 2
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 70
                  level: 50
                  effect: Medium Rising
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_b2:
          - parallel:
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  transition: 2
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 70
                  level: 10
                  effect: Medium Falling
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_a3:
          - parallel:
              - action: light.turn_on
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  brightness_pct: 100
                  kelvin: 3000
                  transition: 2
              - action: light.turn_on
                target:
                  entity_id: light.kitchen_lights
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 130
                  level: 50
                  effect: Medium Rising
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_b3:
          - parallel:
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  transition: 2
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_lights
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 130
                  level: 10
                  effect: Medium Falling
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_a4:
          - parallel:
              - action: light.turn_on
                target:
                  area_id: kitchen
                data:
                  brightness_pct: 100
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 142
                  level: 50
                  effect: Medium Rising
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids
        button_b4:
          - parallel:
              - action: script.turn_off_lights_in_areas
                data:
                  areas:
                    - kitchen
              - action: script.inovelli_blue_notifications
                data:
                  led: All
                  color: 142
                  level: 10
                  effect: Medium Falling
                  duration: 15 Seconds
                  target:
                    device_id:
                      *kitchen_light_switch_device_ids

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    use_blueprint:
      path: rohankapoorcom/sun-based-cover-control.yaml
      input:
        cover_entity: cover.kitchen_shades
        open_status_sensor: binary_sensor.kitchen_window_window_door_is_open
        sunrise_offset: "01:30:00"
        close_delay: 0
        notification_action:
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids

  - id: 44e3bc66-fac6-489a-812f-6d9ddf1bd6a4
    alias: Control the Kitchen Lights by Occupancy Sensor
    description: >
      When the Kitchen is Occupied, turn on the lights.
      When the Kitchen is Unoccupied, turn off all but the cabinet lights.
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.kitchen_motion
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.kitchen_motion
                state: 'off'
            sequence:
              - delay:
                  minutes: 2
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_lights
              - if:
                  - condition: state
                    entity_id: cover.kitchen_shades
                    state: open
                then:
                  - action: light.turn_off
                    target:
                      entity_id: light.kitchen_cabinet_lights
        default:
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.kitchen_lights_load_switch_illuminance
                  below: 40
              then:
                - action: light.turn_on
                  target:
                    entity_id:
                      - light.kitchen_cabinet_lights
            - if:
                - condition: numeric_state
                  entity_id: sensor.kitchen_lights_load_switch_illuminance
                  below: 60
              then:
                - action: light.turn_on
                  target:
                    entity_id:
                      - light.kitchen_lights
    mode: restart

  - id: 89a642f0-805b-4578-9f5b-aa558f5ac35d
    alias: Control the Kitchen Sink Lights by Occupancy Sensor
    description: >
      When the Sink is Occupied, turn on the sink lights.
      When the Sink is Unoccupied, turn off the sink lights.
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.kitchen_sink_occupancy
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.kitchen_sink_occupancy
                state: 'off'
            sequence:
              - delay:
                  seconds: 30
              - action: light.turn_off
                target:
                  entity_id: light.sink_accent_lights
        default:
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.kitchen_lights_load_switch_illuminance
                  below: 200
              then:
                - action: light.turn_on
                  target:
                    entity_id:
                      - light.sink_accent_lights
    mode: restart
