###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen_lights'

      kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
        - 5580d638554510eabf0b5d3dbabe1263
        - 1ba8afa3f33d85ff33d77a5a13dfd364

################################################
## Light
################################################
light:

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Script
################################################
script:
  update_dishwasher_display:
    description: "Update the dishwasher display with the current state"
    fields:
      state:
        description: "The current state of the dishwasher (Clean, Dirty, Running)"
        example: Running
    sequence:
      - action: open_epaper_link.drawcustom
        data:
          background: white
          rotate: 0
          ttl: 300
          dither: false
          payload:
            - type: text
              value: "{{ state }}"
              font: ppb.ttf
              x: 220
              y: 64
              size: 70
              color: red
              anchor: mm
            - type: text
              value: As of {{ now().strftime('%m/%d/%Y at %I:%M %p') }}
              font: ppb.ttf
              x: 375
              y: 160
              size: 15
              color: black
              anchor: rs
            - type: icon
              value: silverware-clean
              x: 40
              y: 64
              size: 60
              color: black
              anchor: mm
            - type: text
              value: Dirty
              font: ppb.ttf
              x: 15
              y: 130
              size: 15
              color: black
              anchor: ls
            - type: text
              value: Clean
              font: ppb.ttf
              x: 100
              y: 130
              size: 15
              color: black
              anchor: ls
            - type: icon
              value: arrow-down
              x: 33
              y: 160
              size: 25
              color: red
              anchor: ms
            - type: icon
              value: arrow-down
              x: 125
              y: 160
              size: 25
              color: red
              anchor: ms
        target:
          device_id:
            - a3f2009d29c8d2526fb0ad4c94097c63

################################################
## Automation
################################################
automation:
  - id: 6eb0e509-5d18-401a-87e1-d05a7b3854f6
    alias: Update Dishwasher Display
    description: "Set Dishwasher Display status based on power usage"
    use_blueprint:
      path: >-
        sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        power_sensor: sensor.energy_monitor_2_dishwasher_power
        starting_threshold: 25
        finishing_threshold: 15
        actions:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        starting_hysteresis: 5
        finishing_hysteresis: 10
        pre_actions:
          - action: script.update_dishwasher_display
            data:
              state: Running

  - id: 035831df-c284-4935-93fd-a337e2890b8c
    alias: Dishwasher Display Button Triggers
    description: Change the dishwasher display based on buttons triggered
    use_blueprint:
      path: rohankapoorcom/solum-m3-epaper-tag-buttons.yaml
      input:
        epaper_tag:
          - a3f2009d29c8d2526fb0ad4c94097c63
        button_1:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        button_2:
          - action: script.update_dishwasher_display
            data:
              state: Dirty

  - id: 3c66912f-0aa1-469f-9b91-93bfa7c2711f
    alias: Kitchen Light Switch Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch: *kitchen_light_switch_device_ids
        config_button:
          - action: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a2:
          - action: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b2:
          - action: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a3:
          - action: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - action: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b3:
          - action: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - action: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a4:
          - action: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b4:
          - action: light.turn_off
            target:
              area_id: kitchen
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    use_blueprint:
      path: rohankapoorcom/sun-based-cover-control.yaml
      input:
        cover_entity: cover.kitchen_shades
        open_status_sensor: binary_sensor.kitchen_windows
        sunrise_offset: "01:30:00"
        close_delay: 0
        notification_action:
          - action: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
