---
blueprint:
  name: Update Dishwasher E-Paper Display
  description: >
    Update an OpenEPaperLink e-paper display with dishwasher status
    (Clean, Dirty, Running) including icons and timestamp.
  domain: script
  input:
    epaper_tag:
      name: E-Paper Tag
      description: The OpenEPaperLink e-paper tag device to update
      required: true
      selector:
        device:
          filter:
            integration: open_epaper_link
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/script/rohankapoorcom/update-dishwasher-epaper-display.yaml
fields:
  state:
    name: State
    description: The current state of the dishwasher (Clean, Dirty, Running)
    example: Running
    required: true
    selector:
      text: {}
sequence:
  - action: open_epaper_link.drawcustom
    data:
      background: white
      rotate: 0
      ttl: 300
      dither: false
      payload:
        - type: text
          value: "{{ state }}"
          font: ppb.ttf
          x: 220
          y: 64
          size: 70
          color: red
          anchor: mm
        - type: text
          value: As of {{ now().strftime('%m/%d/%Y at %I:%M %p') }}
          font: ppb.ttf
          x: 375
          y: 160
          size: 15
          color: black
          anchor: rs
        - type: icon
          value: silverware-clean
          x: 40
          y: 64
          size: 60
          color: black
          anchor: mm
        - type: text
          value: Dirty
          font: ppb.ttf
          x: 15
          y: 130
          size: 15
          color: black
          anchor: ls
        - type: text
          value: Clean
          font: ppb.ttf
          x: 100
          y: 130
          size: 15
          color: black
          anchor: ls
        - type: icon
          value: arrow-down
          x: 33
          y: 160
          size: 25
          color: red
          anchor: ms
        - type: icon
          value: arrow-down
          x: 125
          y: 160
          size: 25
          color: red
          anchor: ms
    target:
      device_id: !input epaper_tag
