---
blueprint:
  name: Lock Light Controls
  description: Turns on a light in response to a lock being unlocked
  domain: automation
  input:
    lock_entity:
      name: Lock Entity
      description: List of available lock entities
      selector:
        entity:
          domain: lock
    light_entity:
      name: Light Entity
      description: List of available lights to turn on
      selector:
        entity:
          domain: light
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/lock-light-controls.yaml
mode: single
max_exceeded: silent
triggers:
  - trigger: state
    entity_id: !input lock_entity
    from: locked
    to: unlocked
actions:
  - action: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_pct: 100
