# Based off of the Home Assistant default motion-light blueprint
# yamllint disable-line rule:line-length
# Original source: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
---
blueprint:
  name: Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/motion_light.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        entity:
          filter:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - trigger: state
    entity_id: !input motion_entity
    from: 'off'
    to: 'on'

actions:
  - choose:
      - alias: If there is motion, then turn on the light_target.
        conditions:
          - condition: state
            entity_id: !input motion_entity
            state: 'on'
        sequence:
          - choose:
              - alias: If the light_target is not on, then turn it on.
                conditions:
                  - condition: state
                    entity_id: !input light_target
                    state: 'off'
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light_target
          - wait_for_trigger:
              - trigger: state
                entity_id: !input motion_entity
                from: 'on'
                to: 'off'
          - delay: !input no_motion_wait
          - action: light.turn_off
            target:
              entity_id: !input light_target
    default:
      - action: light.turn_off
        target:
          entity_id: !input light_target
