esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: wesp32

ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk:
    pin: GPIO00
    mode: CLK_EXT_IN
  phy_addr: 0
  phy_registers:
    - address: 0x10
      value: 0x1FFA
      page_id: 0x07
  domain: ${ethernet_domain}
