###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  01/31/2022
#  @package      :  Living Room / Lights
#  @description  :  Integrates lighting controls in the living room
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'living_room_lights'

      living_room_light_switch_device_id: &living_room_light_switch_device_id
        - 257a7b48517ba7c9cc28fa70842c24f6

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      living_room_fan_slow:
        friendly_name: Living Room Fan Set to Slow
        value_template: >
          {% set living_room_fan_percentage = state_attr('fan.living_room_fan', 'percentage') | int(0) %}
          {{ living_room_fan_percentage > 0 and living_room_fan_percentage <= 52 }}

      living_room_fan_medium:
        friendly_name: Living Room Fan Set to Medium
        value_template: >
          {% set living_room_fan_percentage = state_attr('fan.living_room_fan', 'percentage') | int(0) %}
          {{ living_room_fan_percentage > 52 and living_room_fan_percentage <= 81 }}

      living_room_fan_high:
        friendly_name: Living Room Fan Set to High
        value_template: "{{ state_attr('fan.living_room_fan', 'percentage') | int(0) > 81 }}"

      living_room_fan_off:
        friendly_name: Living Room Fan Set to High
        value_template: "{{ is_state('fan.living_room_fan', 'off') }}"

################################################
## Fan
################################################
fan:
  - platform: template
    fans:
      living_room_fan:
        friendly_name: Living Room Fan
        unique_id: 2e23a699-aa54-49ea-8485-e01faf98275a
        value_template: "{{is_state('light.living_room_fan', 'on')}}"
        percentage_template: >
          {{ (state_attr('light.living_room_fan', 'brightness') | float(0) * 0.392)  | round(0)}}
        turn_on:
          action: light.turn_on
          target:
            entity_id:
              - light.living_room_fan
        turn_off:
          action: light.turn_off
          target:
            entity_id:
              - light.living_room_fan
        set_percentage:
          action: light.turn_on
          data:
            brightness_pct: "{{ percentage }}"
          target:
            entity_id:
              - light.living_room_fan
        speed_count: 3

################################################
## Automation
################################################
automation:
  - id: '8fbfa021-9205-4f56-b3a0-9eea04900c42'
    alias: Living Room Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Living Room.
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: f5f0fa81fd632379a87e70da0c55057f
        scene_1:
          - action: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 100
        scene_2:
          - action: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 65
        scene_4:
          - action: fan.turn_off
            target:
              entity_id: fan.living_room_fan
        scene_3:
          - action: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 27

  - id: '38a41f0a-5b07-4efc-804c-3e19fadc156b'
    alias: Living Room Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller in the Living Room.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: f5f0fa81fd632379a87e70da0c55057f
        large_button_light: light.living_room_lights
        small_1_button_light: binary_sensor.living_room_fan_high
        small_2_button_light: binary_sensor.living_room_fan_medium
        small_3_button_light: binary_sensor.living_room_fan_slow
        small_4_button_light: binary_sensor.living_room_fan_off

  - id: '023bc818-9231-4450-b15b-1dc7692f3fbb'
    alias: Living Room Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Living Room.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device:
          *living_room_light_switch_device_id
        config_button:
          - action: cover.toggle
            data: {}
            target:
              entity_id: cover.living_room_curtains
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_a2:
          - action: cover.open_cover
            data: {}
            target:
              entity_id: cover.living_room_sheers
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_b2:
          - action: cover.close_cover
            data: {}
            target:
              entity_id: cover.living_room_sheers
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close

  - id: 3f0b4ba4-678b-4b37-b956-440b78c98dbe
    alias: Manage the Living Room Curtains
    use_blueprint:
      path: rohankapoorcom/sun-based-cover-control.yaml
      input:
        cover_entity: cover.living_room_curtains
        open_status_sensor: binary_sensor.living_room_windows
        sunrise_offset: "01:30:00"
        close_delay: 5
        notification_action:
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close

  - id: c1febace-175f-47ef-9c1a-3ffe22a96ccf
    alias: Manage Living Room Sheers on Window Close
    description: >-
      Automatically closes the living room sheers when the windows are closed.
      Monitors the living room windows binary sensor state.
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_windows
        to: 'off'
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    conditions:
      - alias: "Safety check: Verify windows are still closed to prevent false triggers"
        condition: template
        value_template: "{{ is_state('binary_sensor.living_room_windows', 'off') }}"
    actions:
      - delay:
          seconds: 5
      - action: cover.close_cover
        target:
          entity_id: cover.living_room_sheers
      - action: zwave_js.bulk_set_partial_config_parameters
        target:
          device_id:
            *living_room_light_switch_device_id
        data:
          parameter: 99
          value:
            All LED Strip Effect - Color: 170
            All LED Strip Effect - Level: 40
            All LED Strip Effect - Duration: 10
            All LED Strip Effect - Effect: Open/close
