---
substitutions:
  device_name: zwave-radio
  friendly_name: Z-Wave Radio

  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password
  ethernet_domain: !secret wifi_domain

packages:
  base: !include packages/base.yaml

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  project:
    name: tubezb.zw
    version: "3.0"

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: "${ethernet_domain}"

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

web_server:
  port: 80

uart:
  id: uart_bus
  rx_pin: GPIO16
  tx_pin: GPIO5
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: ss
  buffer_size: 2048
  port: 6638 # optional, default is 6638

binary_sensor:
  - platform: stream_server
    stream_server: ss
    connected:
      name: "TubesZB Serial Connected"
