###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Doorbell
#  @description  :  Logic for receiving and processing door bell events
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'door_bell'

      media_player_id: &media_player_id
        entity_id: media_player.notifications

      notification_id: &notification_id
        notification_id: 'front_door_bell'

    binary_sensor.front_door_bell:
      <<: *customize

    automation.alert_front_door_bell:
      <<: *customize
    automation.reset_front_door_bell_sensor:
      <<: *customize

    script.reset_front_door_bell_notification:
      <<: *customize
    script.loop_door_bell_font_colors:
      <<: *customize
    script.loop_door_bell_font_colors_loop_control:
      <<: *customize

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: mqtt
    name: front_door_bell
    state_topic: 'tele/rfbridge/RESULT'
    payload_on: '7D35FC'
    payload_off: '7D35FCoff'
    value_template: '{{ value_json.RfReceived.Data }}'

################################################
## Automation
################################################
automation:

  - id: alert_front_door_bell
    alias: Alert Front Door Bell
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_bell
        to: 'on'
    action:
      - service: persistent_notification.create
        data:
          message: 'Front Doorbell Ringing'
          <<: *notification_id
      - service: media_player.play_media
        <<: *media_player_id
        data:
          media_content_id: !secret media_content_id.front_door_bell
          media_content_type: audio/mp3
      - service: script.plates_p0_display_text_message
        data:
          text: 'Doorbell Ringing!'
      - service: script.loop_door_bell_font_colors
      - delay:
          seconds: 15
      - service: script.reset_front_door_bell_notification

  - id: reset_front_door_bell_sensor
    alias: Reset Front Door Bell Sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_bell
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: 'tele/rfbridge/RESULT'
          payload: >-
            {
              "RfReceived": {
                "Data": "7D35FCoff"
              }
            }
          retain: 'true'

################################################
## Script
################################################
script:

  reset_front_door_bell_notification:
    sequence:
      - service: persistent_notification.dismiss
        data:
          <<: *notification_id
      - service: media_player.media_stop
        <<: *media_player_id
      - service: script.plates_p0_reset_screen
      - service: script.turn_off
        entity_id: script.loop_door_bell_font_colors
      - service: script.turn_off
        entity_id: script.loop_door_bell_font_colors_loop_control
      - service: python_script.hasp_update_colors
        data:
          nodename: plates
          object_id: 'p[0].b[1]'
          background: '65535'
          foreground: '25388'

  loop_door_bell_font_colors:
    sequence:
      - service: python_script.hasp_update_colors
        data:
          nodename: plates
          object_id: 'p[0].b[1]'
          background: '63488'
          foreground: '65535'
      - service: script.turn_off
        entity_id: script.loop_door_bell_font_colors_loop_control
      - delay:
          milliseconds: 500
      - service: python_script.hasp_update_colors
        data:
          nodename: plates
          object_id: 'p[0].b[1]'
          background: '2016'
          foreground: '0'
      - service: script.loop_door_bell_font_colors_loop_control

  loop_door_bell_font_colors_loop_control:
    sequence:
      - service: script.turn_off
        entity_id: script.loop_door_bell_font_colors
      - delay:
          milliseconds: 500
      - service: script.loop_door_bell_font_colors

