###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: group
    name: Downstairs Hallway Motion
    unique_id: 4efe0f31-8bf8-426e-8eb1-31cd59f889e4
    device_class: motion
    entities:
      - binary_sensor.downstairs_hallway_lights_load_switch_occupancy

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Downstairs Hallway Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablets_battery_combined
        switch_entity: switch.downstairs_hallway_tablet_charger

  - id: '1667032713651'
    alias: Downstairs Hallway Scene Controls
    description: Utilizes a blueprint to control scenes in the Downstairs Hallway.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - cd886aa54686a23eb0ef9ea9a5fb0d20
        config_button:
          - action: button.press
            data: {}
            target:
              entity_id: button.downstairs_hallway_tablet_restart_browser
        button_a2:
          - action: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tablet_charger
        button_b2:
          - action: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tv

  - id: 60f9f9b9-ef6e-494d-af89-fd43cdc92d9e
    alias: Control the Downstairs Hallway TV
    description: Turn the Downstairs Hallway TV on/off due to Roku state changes
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: media_player.roku_streambar
        to: 'on'
      - trigger: state
        entity_id: media_player.roku_streambar
        to: 'idle'
        for:
          minutes: 10
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'idle'
            sequence:
              - action: switch.turn_off
                entity_id: switch.downstairs_hallway_tv
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'on'
            sequence:
              - action: switch.turn_on
                entity_id: switch.downstairs_hallway_tv

  - id: 825c80a1-794c-4f3c-95a9-077ebee85d58
    alias: Update Water Heater Cleaning Status
    description: Show the last cleaning time on the water heater display
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: input_datetime.water_heater_last_cleaning
    actions:
      - wait_template: "{{ not is_state('sensor.0000021f85043b1c_last_seen', 'unavailable') }}"
        timeout: 00:05:00
        continue_on_timeout: false
      - action: open_epaper_link.drawcustom
        data:
          background: white
          rotate: 0
          ttl: 300
          dither: false
          payload:
            - type: text
              value: "Last Cleaned"
              font: ppb.ttf
              x: 148
              "y": 32
              size: 30
              color: red
              anchor: mm
            - type: text
              value: "{{ (states('input_datetime.water_heater_last_cleaning') | as_datetime).strftime('%a %m/%d/%Y') }}"
              font: ppb.ttf
              x: 148
              "y": 96
              size: 30
              color: red
              anchor: mm
            - type: line
              x_start: 0
              x_end: 296
              y_start: 64
              y_end: 64
              width: 5
              fill: black
        target:
          device_id:
            - 92fdfab08e59b30ec43c0b56f90207e0

  - id: 8c282f4e-961c-47d1-9684-cbdef479d216
    alias: Control the Under Stairs Closet Lights
    description: Utilizes the motion_light blueprint for controlling the Under Stairs Closet Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.under_stairs_closet_door_window_door_is_open
        light_target: light.under_stairs_closet_lights
        no_motion_wait: 0
