###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/23/2021
#  @package      :  Garage
#  @description  :  Automations in the Garage
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'garage'

################################################
## Light
################################################
light:
  - platform: switch
    name: Garage Lights
    entity_id: switch.garage_lights

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: group
    name: Garage Motion
    unique_id: e0fcd27b-7ca9-42c3-815e-63d15f0795ed
    device_class: motion
    entities:
      - binary_sensor.garage_lights_motion
      - binary_sensor.garage_multisensor_motion

automation:
  - id: 8cbaf941-3de6-482e-9226-fbe103e7c84e
    alias: Control the Garage Lights
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.garage_motion
        from: 'off'
        to: 'on'
      - trigger: state
        entity_id: cover.garage_door
        from: 'closed'
        to: 'opening'
    actions:
      - choose:
          - alias: If there is motion, the garage door is opening or open, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.garage_motion
                    state: 'on'
                  - condition: state
                    entity_id: cover.garage_door
                    state: 'opening'
                  - condition: state
                    entity_id: cover.garage_door
                    state: 'open'
            sequence:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.garage_lights
                    - light.garage_door_light
              - action: switch.turn_on
                target:
                  entity_id:
                    - switch.garage_tablet_screen
              - wait_for_trigger:
                  - trigger: template
                    value_template: >
                      {{ is_state('cover.garage_door', 'closed')
                      and is_state('binary_sensor.garage_motion', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 10
              - action: light.turn_off
                target:
                  entity_id:
                    - light.garage_lights
                    - light.garage_door_light
              - action: switch.turn_off
                target:
                  entity_id:
                    - switch.garage_tablet_screen
        default:
          - action: light.turn_off
            target:
              entity_id:
                - light.garage_lights
                - light.garage_door_light
          - action: switch.turn_off
            target:
              entity_id:
                - switch.garage_tablet_screen

  - id: c0f6513b-6fac-4e3b-bf92-0399e75e67f5
    alias: Control the Garage Entry Lights
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.garage_entry_motion_sensor
        from: 'off'
        to: 'on'
      - trigger: state
        entity_id: cover.garage_door
        from: 'closed'
        to: 'opening'
    actions:
      - choose:
          - alias: If it's dark and (there is motion or the garage door is opening or open), then turn on the lights.
            conditions:
              - condition: and
                conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: binary_sensor.garage_entry_motion_sensor
                        state: 'on'
                      - condition: state
                        entity_id: cover.garage_door
                        state: 'opening'
                      - condition: state
                        entity_id: cover.garage_door
                        state: 'open'
                  - condition: numeric_state
                    entity_id: sensor.garage_entry_motion_sensor_illuminance
                    below: 100

            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.garage_entry_lights
              - wait_for_trigger:
                  - trigger: template
                    value_template: >
                      {{ is_state('cover.garage_door', 'closed')
                      and is_state('binary_sensor.garage_entry_motion_sensor', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 1
              - action: light.turn_off
                target:
                  entity_id: light.garage_entry_lights
        default:
          - action: light.turn_off
            entity_id: light.garage_entry_lights

  - id: '1649035604702'
    alias: Garage Scene Controller Scene Controls
    description: 'Utilizes a blueprint to control scenes in the garage.'
    use_blueprint:
      path: IOT_Ninja/zooz-zen30-double-switch-automation-helper.yaml
      input:
        zooz_zen30: 91a73ad6fd7d0c4885fedd856cf2701d
        relay_1x:
          - action: light.turn_off
            target:
              area_id:
                - hallway_bathroom
                - living_room
                - kitchen
                - dining_room
                - master_bathroom
                - master_bedroom
                - office
                - downstairs_bathroom
                - downstairs_hallway
                - guest_room
                - gym
        relay_2x:
          - action: light.turn_off
            target:
              area_id:
                - hallway
                - hallway_bathroom
                - living_room
                - kitchen
                - dining_room
                - master_bathroom
                - master_bedroom
                - office
                - downstairs_bathroom
                - downstairs_hallway
                - guest_room
                - gym
