###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/23/2021
#  @package      :  Garage
#  @description  :  Automations in the Garage
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'garage'

################################################
## Light
################################################
light:
  - platform: switch
    name: Garage Lights
    entity_id: switch.garage_lights

automation:
  - id: 8cbaf941-3de6-482e-9226-fbe103e7c84e
    alias: Control the Garage Lights
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id: binary_sensor.garage_lights_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: cover.garage_door
        from: 'closed'
        to: 'opening'
    action:
      - choose:
          - alias: If there is motion, the garage door is opening or open, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.garage_lights_motion
                    state: 'on'
                  - condition: state
                    entity_id: cover.garage_door
                    state: 'opening'
                  - condition: state
                    entity_id: cover.garage_door
                    state: 'open'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.garage_lights
              - wait_for_trigger:
                  - platform: template
                    value_template: >
                      {{ is_state('cover.garage_door', 'closed')
                      and is_state('binary_sensor.garage_lights_motion', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 10
              - service: light.turn_off
                target:
                  entity_id: light.garage_lights
        default:
          - service: light.turn_off
            entity_id: light.garage_lights
