###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Gym
#  @description  :  Manages equipment in the Gym.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: dd25ecc8-aaee-4a32-8b38-90b13db78b09
    alias: Control the Gym Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.gym_tablet_battery
        switch_entity: switch.gym_tablet_charger

  - id: '1667032908768'
    alias: Gym Scene Controls
    description: Utilizes a blueprint to control scenes with the Gym Lightswitch.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device: 4ef91ee5285ec4ad43cb3dbf25b3faf7
        config_button:
          - action: cover.toggle
            target:
              entity_id: cover.gym_shades
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id: 4ef91ee5285ec4ad43cb3dbf25b3faf7
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 20
                All LED Strip Effect - Effect: Open/close
        config_button2:
          - action: button.press
            data: {}
            target:
              entity_id:
                - button.gym_tablet_restart_browser
        button_a2:
          - action: fan.turn_on
            data: {}
            target:
              entity_id: fan.gym_fan
        button_b2:
          - action: fan.turn_off
            data: {}
            target:
              entity_id: fan.gym_fan

  - use_blueprint:
      path: rohankapoorcom/sun-based-cover-control.yaml
      input:
        cover_entity: cover.gym_shades
        open_status_sensor: binary_sensor.gym_sliding_door_window_door_is_open
        sunrise_offset: "01:30:00"
        close_delay: 0
        notification_action:
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id: 4ef91ee5285ec4ad43cb3dbf25b3faf7
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 20
                All LED Strip Effect - Effect: Open/close
