###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/11/2018
#  @package      :  HA System
#  @description  :  Manages aspects of the home assistant system
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ha_system'

      command_line_sensor_default: &defaults
        scan_interval: 10
        command_timeout: 5

    sensor.rohankapoorcomhomeassistantconfig_last_build_state:
      <<: *customize

    sensor.current_git_commit_id:
      <<: *customize

    sensor.current_git_commit_time:
      <<: *customize

    sensor.current_version:
      <<: *customize

    sensor.desired_version:
      <<: *customize

    sensor.upgraded_version:
      <<: *customize

    automation.update_configuration_if_travis_build_is_successful:
      <<: *customize

    shell_command.git_pull:
      <<: *customize

    shell_command.update_homeassistant:
      <<: *customize

    script.pull_and_restart_homeassistant:
      <<: *customize

    script.update_homeassistant:
      <<: *customize

################################################
## Sensor
################################################

sensor:

  - platform: travisci
    api_key: !secret sensor.travis.api_key
    repository:
      - homeassistant-config
    branch:
      - master
    monitored_conditions:
      - last_build_state

  - platform: command_line
    <<: *defaults
    name: current_git_commit_id
    command: '/usr/bin/git -C /etc/homeassistant/ rev-parse HEAD'

  - platform: command_line
    <<: *defaults
    name: current_git_commit_time
    command: '/usr/bin/git -C /etc/homeassistant/ log -1 --format="%at" | /usr/bin/xargs -I{} /bin/date -ud @{} +"%Y-%m-%dT%H:%M:%S.000Z"'

  - platform: version
    <<: *defaults
    name: current_version

  - platform: command_line
    <<: *defaults
    name: desired_version
    command: '/bin/cat /etc/homeassistant/.HA_VERSION'

  - platform: command_line
    <<: *defaults
    name: upgraded_version
    command: '/srv/homeassistant/bin/hass --version'

################################################
## Automation
################################################

automation:

  - id: update_configuration_if_travis_build_is_successful
    alias: Update configuration if travis build is successful
    trigger:
      - entity_id: sensor.rohankapoorcomhomeassistantconfig_last_build_state
        platform: state
        to: 'passed'
    condition:
      - condition: template
        value_template: "{{ is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit Branch', 'master') }}"
      - condition: template
        value_template: "{{ not is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit SHA', states('sensor.current_git_commit_id')) }}"
      - condition: template
        value_template: "{{ states('sensor.current_git_commit_time') < state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Committed Date') }}"
    action:
      - service: script.pull_and_restart_homeassistant

################################################
## Shell Command
################################################

shell_command:
  git_pull: "/usr/bin/git -C /etc/homeassistant/ pull"
  update_homeassistant: "/bin/bash /etc/homeassistant/bash_scripts/update.sh -u {{ states('sensor.desired_version') }}"

################################################
## Script
################################################

script:

  pull_and_restart_homeassistant:
    sequence:
      - service: shell_command.git_pull
      - wait_template: "{{ is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit SHA', states('sensor.current_git_commit_id')) }}"
      - delay:
          seconds: 30 # Wait for all command line sensors to be updated
      - service: script.update_homeassistant
      - wait_template: "{{ is_state('sensor.upgraded_version', states('sensor.desired_version')) }}"
      - service: homeassistant.restart

  update_homeassistant:
    sequence:
      - condition: template
        value_template: "{{ states('sensor.current_version') < states('sensor.desired_version') }}"
      - service: shell_command.update_homeassistant
