###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################
    light.hallway_lights:
      <<: *customize


################################################
## Light
################################################
light:
  - platform: group
    name: Hallway Lights
    entities:
      - light.hallway_lights_switch
      - light.entryway_lights
