###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

################################################
## Automations
################################################
automation:
  - id: 0de6a925-9ceb-42fb-b7be-f6621be3ed09
    alias: Control the Upstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Hallway Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.upstairs_hallway_tablet_battery
        switch_entity: switch.upstairs_hallway_tablet_charger

  - id: '1643337826040'
    alias: Upstairs Hallway Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Upstairs Hallway.
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        scene_1:
          - action: light.toggle
            target:
              entity_id: light.dining_room_lights
        scene_2:
          - action: light.toggle
            target:
              entity_id: light.dining_room_accent_lights
        scene_3:
          - action: light.toggle
            target:
              entity_id: light.kitchen_lights
        scene_4:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.kitchen_cabinet_lights
                    state: 'on'
                sequence:
                  - action: light.turn_off
                    target:
                      entity_id: light.kitchen_cabinet_lights
                    data:
                      transition: 2
            default:
              - action: light.turn_on
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  brightness_pct: 100
                  kelvin: 3000
                  transition: 2
        scene_5:
          - action: light.toggle
            target:
              entity_id: light.hallway_lights

  - id: '1643339651442'
    alias: Upstairs Hallway Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller in the Upstairs Hallway.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        large_button_light: light.hallway_lights
        small_1_button_light: light.dining_room_lights
        small_2_button_light: light.dining_room_accent_lights
        small_3_button_light: light.kitchen_lights
        small_4_button_light: light.kitchen_cabinet_lights

  - id: 56be5167-15a8-4243-ae8d-c4b8b82b3e9e
    alias: Control the Hallway Closet Lights
    description: Utilizes the motion_light blueprint for controlling the Hallway Closet Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.upstairs_hallway_closet_door_window_door_is_open
        light_target: light.upstairs_hallway_closet_lights
        no_motion_wait: 0

  - id: '1717577172306'
    alias: Hallway Outside Master Bedroom Scene Controls
    description: >-
      Scene controls in the hallway outside the master bedroom using Inovelli
      Blue Series switch with LED notifications for visual feedback
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - cf7f37ae8d16893c8c78e6d0e6fe3b24
        config_button:
          - action: script.turn_off_lights_in_areas
            data:
              areas:
                - upstairs_hallway_closet
                - hallway
                - hallway_bathroom
                - kitchen
                - living_room
                - office
          - action: script.inovelli_blue_notifications
            metadata: {}
            data:
              led: All
              color: Teal
              effect: Fast Falling
              duration: 10 Seconds
              target:
                device_id: cf7f37ae8d16893c8c78e6d0e6fe3b24
              level: 30
