###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Lighting Effects
#  @description  :  Scripts used for various lighting effects
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'lighting_effects'

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.random_color_loop:
      <<: *customize

    ################################################
    ## Input Select
    ################################################
    input_select.random_color_loop_location:
      <<: *customize

    ################################################
    ## Input Number
    ################################################
    input_number.random_color_loop_min_brightness:
      <<: *customize

    input_number.random_color_loop_max_brightness:
      <<: *customize

    input_number.random_color_loop_transition_speed:
      <<: *customize

    ################################################
    ## Group
    ################################################
    group.lighting_effects:
      <<: *customize

    ################################################
    ## Light
    ################################################
    light.downstairs_color_lights:
      <<: *customize
      location: Downstairs

    light.upstairs_color_lights:
      <<: *customize
      location: Upstairs

    light.all_color_lights:
      <<: *customize
      location: All

    ################################################
    ## Automation
    ################################################
    automation.start_random_color_loop:
      <<: *customize

    automation.stop_random_color_loop:
      <<: *customize

    ################################################
    ## Script
    ################################################
    script.random_color_loop:
      <<: *customize

    script.random_color_loop_control:
      <<: *customize

################################################
## Input Boolean
################################################
input_boolean:
  random_color_loop:
    name: Color Fade
    initial: false
    icon: mdi:invert-colors

################################################
## Input Select
################################################
input_select:
  random_color_loop_location:
    name: Location
    options:
      - All
      - Downstairs
      - Upstairs
    initial: All
    icon: mdi:radar

################################################
## Input Number
################################################
input_number:

  random_color_loop_min_brightness:
    name: Minimum Brightness
    initial: 0
    min: 0
    max: 100
    step: 1
    icon: mdi:lightbulb-outline

  random_color_loop_max_brightness:
    name: Maximum Brightness
    initial: 100
    min: 0
    max: 100
    step: 1
    icon: mdi:lightbulb-on-outline

  random_color_loop_transition_speed:
    name: Transition Time
    initial: 1.5
    min: 1
    max: 10
    step: 0.5
    unit_of_measurement: second
    icon: mdi:speedometer

################################################
## Automation
################################################
automation:

  - id: start_random_color_loop
    alias: Start Random Color Loop
    trigger:
      - platform: state
        entity_id: input_boolean.random_color_loop
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
      - service: script.random_color_loop

  - id: stop_random_color_loop
    alias: Stop Random Color Loop
    trigger:
      - platform: state
        entity_id: input_boolean.random_color_loop
        to: 'off'
    action:
      - service: script.turn_off
        entity_id: script.random_color_loop
      - service: script.turn_off
        entity_id: script.random_color_loop_control
        # Todo store/reset lights affected

################################################
## Script
################################################
script:

  random_color_loop:
    sequence:
      # Pick random color
      - service: light.turn_on
        data_template:
          # This should only evaluate to one lightgroup
          entity_id: >
            {%- for item in states.light if (
              is_state_attr(item.entity_id, 'location', states('input_select.random_color_loop_location'))
              )
            -%}
              {{ item.entity_id }}
            {%- endfor -%}
          rgb_color: >
            ['{{ (range(0, 255) | random) }}' , '{{ (range(0, 255) | random) }}' , '{{ (range(0, 255) | random) }}']
          brightness_pct: >-
            {% set left = states('input_number.random_color_loop_min_brightness') | int %}
            {% set right = states('input_number.random_color_loop_max_brightness') | int %}
            {% if left < right %}
              {{ (range(left, right + 1) | random) }}
            {% else %}
              {{ (range(right, left + 1) | random) }}
            {% endif %}
          transition: "{{ states('input_number.random_color_loop_transition_speed') | float }}"
      - service: script.turn_off
        entity_id: script.random_color_loop_control
      - delay:
          milliseconds: "{{ (((states('input_number.random_color_loop_transition_speed') | float) / 2) * 1000) | int }}"
      - service: script.random_color_loop_control

  random_color_loop_control:
    sequence:
      - service: script.turn_off
        entity_id: script.random_color_loop
      - delay:
          milliseconds: "{{ (((states('input_number.random_color_loop_transition_speed') | float) / 2) * 1000) | int }}"
      - service: script.random_color_loop
