###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/25/2021
#  @package      :  Master Bathroom
#  @description  :  Controls lights and fans in the Master Bathroom.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'bathroom'


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      master_bathroom_relative_humidity:
        friendly_name: 'Relative Humidity'
        unit_of_measurement: '%'
        value_template: '{{ states.sensor.master_bathroom_humidity.state|float - states.sensor.master_bedroom_humidity.state|float }}'


################################################
## Automation
################################################
automation:
  - id: c9bf0f4b-2f8a-4e9d-a87e-32da42f33608
    alias: Control the Master Bathroom Lights
    description: Utilizes the motion_light blueprint for contolling the Master Bathroom Lights.
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.master_bathroom_motion
        light_target:
          entity_id: light.master_bathroom_lights
        no_motion_wait: 300

  - id: b281c2da-67a2-44b3-a11f-11d763a4ba46
    alias: Control the Master Bathroom Fan
    description: Utilizes motion and humidity for controlling the Master Bathroom Fan.
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bathroom_motion
        from: 'off'
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.master_bathroom_relative_humidity
        above: 20
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.master_bathroom_fan
      - wait_for_trigger:
          platform: template
          value_template: >
            {{ states('sensor.master_bathroom_relative_humidity') | float <= 10
               and is_state('binary_sensor.master_bathroom_motion', 'off') }}
      - delay: 300
      - service: switch.turn_off
        target:
          entity_id: switch.master_bathroom_fan