###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/08/2023
#  @package      :  Master Bedroom
#  @description  :  Manages functionality within the Master Bedroom
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'master_bedroom'

      master_bedroom_light_switch_device_id: &master_bedroom_light_switch_device_id
        - 9a1774a5d28bf6aa7c84198969517bd0

################################################
## Fan
################################################
fan:
  - platform: template
    fans:
      master_bedroom_fan:
        friendly_name: Master Bedroom Fan
        unique_id: e7adcd00-14ac-4b1b-8366-5951aacd1482
        value_template: "{{is_state('light.master_bedroom_fan', 'on')}}"
        percentage_template: >
          {{ (state_attr('light.master_bedroom_fan', 'brightness') | float(0) * 0.392)  | round(0)}}
        turn_on:
          action: light.turn_on
          target:
            entity_id:
              - light.master_bedroom_fan
        turn_off:
          action: light.turn_off
          target:
            entity_id:
              - light.master_bedroom_fan
        set_percentage:
          action: light.turn_on
          data:
            brightness_pct: "{{ percentage }}"
          target:
            entity_id:
              - light.master_bedroom_fan
        speed_count: 3

################################################
## Script
################################################
script:
  turn_on_watch_master_bedroom_tv:
    alias: Turn on the Master Bedroom TV
    sequence:
      - action: media_player.turn_on
        target:
          entity_id:
            - media_player.master_bedroom_tv
            - media_player.denon_avr_x4300h_zone_2
            - media_player.shield
      - action: media_player.select_source
        target:
          device_id: ab65d3019b2049668b610bf0c5bc58c2
        data:
          source: HDMI-1
      - action: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?Z2QUICK1
      - action: androidtv.adb_command
        data:
          entity_id: media_player.living_room_shield_tv
          command: HOME
    mode: single
    icon: mdi:television

  turn_on_watch_master_bedroom_apple_tv:
    alias: Turn on the Master Bedroom TV
    sequence:
      - action: media_player.turn_on
        target:
          entity_id:
            - media_player.master_bedroom_tv
            - media_player.denon_avr_x4300h_zone_2
            - media_player.living_room_apple_tv
      - action: media_player.select_source
        target:
          device_id: ab65d3019b2049668b610bf0c5bc58c2
        data:
          source: HDMI-1
      - action: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?Z2QUICK2
      - action: remote.send_command
        target:
          entity_id: remote.living_room_apple_tv
        data:
          delay_secs: 1
          command:
            - wakeup
            - home
    mode: single
    icon: mdi:television

  turn_off_the_master_bedroom_tv:
    alias: Turn off the Master Bedroom TV
    sequence:
      - action: media_player.turn_off
        target:
          entity_id:
            - media_player.master_bedroom_tv
            - media_player.denon_avr_x4300h_zone_2
            - media_player.shield
    mode: single
    icon: mdi:television-off

  turn_on_the_master_bedroom_tv_light_sync:
    alias: Turn on the Master Bedroom TV Syncbox
    sequence:
      - choose:
          - conditions:
              - alias: If the sync box is already running, then stop it.
                condition: state
                entity_id: switch.living_room_sync_box_light_sync
                state: 'on'
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.living_room_sync_box_light_sync
        default:
          - action: rest_command.set_philips_hue_syncbox_input_master_bedroom
          - action: select.select_option
            data:
              option: Master Bedroom
            target:
              entity_id: select.living_room_sync_box_entertainment_area
          - action: switch.turn_on
            target:
              entity_id: switch.living_room_sync_box_light_sync

################################################
## Automation
################################################
automation:
  - id: '1678811559535'
    alias: Master Bedroom Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Master Bedroom.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device:
          *master_bedroom_light_switch_device_id
        config_button:
          - action: cover.toggle
            data: {}
            target:
              entity_id: cover.master_bedroom_curtains
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *master_bedroom_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_a2:
          - action: cover.open_cover
            data: {}
            target:
              entity_id: cover.master_bedroom_sheers
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *master_bedroom_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_b2:
          - action: cover.close_cover
            data: {}
            target:
              entity_id: cover.master_bedroom_sheers
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *master_bedroom_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close

  - id: b605d39d-f08d-4631-be1a-bef89a4f560f
    alias: Manage the Master Bedroom Curtains
    description: Automatically open/close the Master Bedroom Curtains based on the Sun Position
    use_blueprint:
      path: rohankapoorcom/sun-based-cover-control.yaml
      input:
        cover_entity: cover.master_bedroom_curtains
        open_status_sensor: binary_sensor.master_bedroom_sliding_door_window_door_is_open
        sunrise_offset: "01:30:00"
        close_delay: 0
        presence_sensor: binary_sensor.master_bedroom_bed_presence_bed_occupied_either
        notification_action:
          - action: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *master_bedroom_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close

  - id: 8347dcbb-ff95-4565-9b51-667d405c955c
    alias: Control the Master Bedroom TV Remote when Charging
    description: Turn off the motion detection and screen when the Master Bedroom TV Remote is charging.
    mode: single
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.master_bedroom_tv_remote_plugged_in
    actions:
      - choose:
          - alias: If the Master Bedroom TV Remote is charging, turn off the motion detection and screen
            conditions:
              - condition: state
                entity_id: binary_sensor.master_bedroom_tv_remote_plugged_in
                state: 'on'
            sequence:
              - action: switch.turn_off
                entity_id: switch.master_bedroom_tv_remote_motion_detection
              - action: switch.turn_off
                entity_id: switch.master_bedroom_tv_remote_screen
        default:
          - action: switch.turn_on
            entity_id: switch.master_bedroom_tv_remote_motion_detection
          - action: switch.turn_on
            entity_id: switch.master_bedroom_tv_remote_screen
