###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/06/2018
#  @package      :  Media / Music
#  @description  :  Controls the Chromecast Audio devices and integrates them
#                   with Harmony. Speakers power on and off automatically
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'media_music'

################################################
## Emulated Roku
################################################
emulated_roku:
  servers:
    - name: !secret emulated_roku.name
      listen_port: !secret emulated_roku.listen_port
      host_ip: !secret emulated_roku.host_ip

################################################
## Media Player
################################################
media_player:
  - platform: universal
    name: All Speakers
    children:
      - media_player.whole_house

################################################
## Template
################################################
template:
  - sensor:
      - unique_id: d4e5f6a7-b8c9-4012-d345-678901234567
        name: Title
        default_entity_id: sensor.all_speakers_media_title
        state: "{{ state_attr('media_player.all_speakers', 'media_title') }}"
      - unique_id: e5f6a7b8-c9d0-4123-e456-789012345678
        name: Artist
        default_entity_id: sensor.all_speakers_media_artist
        state: "{{ state_attr('media_player.all_speakers', 'media_artist') }}"

