###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/30/2018
#  @package      :  Media / TV
#  @description  :  Integrates lighting and the Harmony Remote for TV/Movies
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_tv'

media_player:
  - platform: androidtv
    name: Living Room Shield TV
    host: !secret media_player.living_room_shield_tv.host

notify:
  - platform: nfandroidtv
    name: Living Room Shield Tv
    host: !secret media_player.living_room_shield_tv.host

################################################
## Automation
################################################
automation:
  - id: faea6bc6-9c9b-439c-9f5a-ac65fbec8cdf
    alias: Handle Shield Emulated Roku Harmony Commands
    description: Executed commands on the Living Room Shield TV in response to Emulated Roku events from the Harmony Hub
    use_blueprint:
      path: rohankapoorcom/emulated-roku.yaml
      input:
        emulated_roku_name: 4t8k7RAjE3TBcfheQvCATZ
        up_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: Netflix
        right_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: Plex
        down_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: YouTube
        left_action:
          - service: androidtv.adb_command
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              # yamllint disable-line rule:line-length
              command: "am start -a android.intent.action.VIEW -d -n com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity"
        home_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: "com.hbo.hbonow"
        search_action:
          - service: androidtv.adb_command
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              command: SEARCH

  - id: c8ff656a-e0d6-4b26-9840-0da9863b1867
    alias: Living Room Shield TV Notify Washer
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_wash_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Washer Complete
          message: The washer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: e2f38056-ce90-46ca-8138-51a9637e3e50
    alias: Living Room Shield TV Notify Dryer
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_dry_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Dryer Complete
          message: The dryer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: c34228e0-c6c9-431f-ad73-cef94537ca2c
    alias: Living Room TV Notify Phone Call
    trigger:
      - platform: state
        entity_id: sensor.line_103_status
        to: 'incoming'
    action:
      - service: notify.living_room_shield_tv
        data_template:
          title: Incoming Phone Call
          message: >
            {{ states('sensor.line_103_caller_name')}} - {{states('sensor.line_103_caller_number') }}
          data:
            duration: 25
            position: top-right
            transparency: 50%
