###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Notifications
#  @description  :  Manages all notification systems (text, voice, etc)
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notifications'

      media_player_notifications: &media_player_notifications
        entity_id: media_player.notifications

      media_player_all_speakers: &media_player_all_speakers
        entity_id: media_player.all_speakers

    automation.keep_notifications_awake:
      <<: *customize

tts:
  platform: google_translate

mailgun:
  domain: !secret mailgun.domain
  api_key: !secret mailgun.api_key

notify:
  - name: FirebasePush
    platform: html5
    vapid_prv_key: !secret notify.gcm.vapid_prv_key
    vapid_pub_key: !secret notify.gcm.vapid_pub_key
    vapid_email: !secret notify.gcm.vapid_email

  - name: rohan_email
    platform: mailgun
    recipient: !secret notify.rohan_email.recipient
    sender: !secret notify.rohan_email.sender

################################################
## Automation
################################################
automation:
  # Google homes go to sleep and then make an annoying wake up sound,
  # Now they stay awake
  - id: keep_notifications_awake
    alias: Keep Notifications Awake
    trigger:
      - platform: time_pattern
        minutes: '/2'
    condition:
      - condition: or
        conditions:
          - condition: state
            <<: *media_player_notifications
            state: 'off'
          - condition: state
            <<: *media_player_notifications
            state: 'idle'
    action:
      - service: media_player.play_media
        <<: *media_player_notifications
        data:
          media_content_id: !secret media_content_id.1second_silence
          media_content_type: audio/mp3

  - id: keep_all_speakers_awake
    alias: Keep All Speakers Awake
    trigger:
      - platform: time_pattern
        minutes: '/2'
    condition:
      - condition: or
        conditions:
          - condition: state
            <<: *media_player_all_speakers
            state: 'off'
          - condition: state
            <<: *media_player_all_speakers
            state: 'idle'
    action:
      - service: media_player.play_media
        <<: *media_player_all_speakers
        data:
          media_content_id: !secret media_content_id.1second_silence
          media_content_type: audio/mp3
