###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  11/28/2020
#  @package      :  Office
#  @description  :  Manages functionality within the office
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'office'


################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      streaming_lights_enabled:
        friendly_name: Streaming Lights Enabled
        value_template: >-
          {{ is_state_attr('light.elgato_key_light_dbc2', 'brightness', 51)
            and is_state_attr('light.elgato_key_light_dbc2', 'color_temp', 143)
            and is_state_attr('light.office_lights', 'brightness', 129)
          }}

################################################
## Input Boolean
################################################
input_boolean:
  sentinal_headset_enabled:
    name: Sentinal Headset Enabled
    icon: mdi:headset

################################################
## Script
################################################
script:
  toggle_streaming_lights:
    sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: binary_sensor.streaming_lights_enabled
            state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.office_lights
            - service: light.turn_off
              entity_id: light.elgato_key_light_dbc2
        default:
          - service: light.turn_on
            data:
              entity_id: light.office_lights
              brightness_pct: 50
          - service: light.turn_on
            entity_id: light.elgato_key_light_dbc2
            data:
              color_temp: 143
              brightness_pct: 20

################################################
## Automation
################################################
automation:
  - id: 0c527fe1-216b-4ace-8e81-004fe00484b9
    alias: Toggle Sentinal Headset
    description: Switches Sentinal to route voice communication audio over to the Jabra Headset or the Ceiling Speakers
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.sentinal_headset_enabled
    action:
      - service: switch.turn_on
        target:
          entity_id: >
            {% if trigger.to_state == 'on' %}
              switch.sentinal_enable_headset
            {% else %}
              switch.sentinal_enable_speakers
            {% endif %}