###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  11/28/2020
#  @package      :  Office
#  @description  :  Manages functionality within the office
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'office'

mqtt_discoverystream_alt:
  - base_topic: homeassistant-bitfocus-companion
    publish_attributes: true
    publish_timestamps: false
    publish_discovery: true
    include:
      entities:
        - binary_sensor.office_fan_high
        - binary_sensor.office_fan_is_off
        - binary_sensor.office_fan_medium
        - binary_sensor.office_fan_slow
        - binary_sensor.office_lights_100_percent
        - binary_sensor.office_lights_25_percent
        - binary_sensor.office_lights_50_percent
        - binary_sensor.office_lights_75_percent
        - button.standing_desk_preset_1
        - button.standing_desk_preset_2
        - button.standing_desk_preset_3
        - button.standing_desk_preset_4
        - input_boolean.office_streamdecks
        - input_boolean.sentinal_headset_enabled
        - light.center_key_light
        - light.left_key_light
        - light.office_backlighting
        - light.office_desk_lower_lights
        - light.office_play_gradient_tube
        - light.office_shelf_lightstrip
        - light.office_video_lights
        - number.office_headphones_chromecast_level
        - number.office_headphones_hyperdeck_level
        - number.office_headphones_mac_level
        - number.office_headphones_pc_level
        - number.office_speakers_hyperdeck_level
        - number.office_speakers_mac_level
        - number.office_speakers_pc_level
        - script.set_office_fan_high
        - script.set_office_fan_medium
        - script.set_office_fan_off
        - script.set_office_fan_slow
        - script.set_office_lights_100_percent
        - script.set_office_lights_25_percent
        - script.set_office_lights_50_percent
        - script.set_office_lights_75_percent
        - sensor.living_room_air_quality_score
        - sensor.office_humidity
        - sensor.office_illuminance
        - sensor.office_speakers_volume
        - sensor.office_temperature
        - sensor.standing_desk_desk_height
        - switch.office_ceiling_mics_mute
        - switch.office_computers_in_kitchen_mute
        - switch.office_computers_in_living_room_mute
        - switch.office_computers_in_master_suite_mute
        - switch.office_headphones_chromecast_mute
        - switch.office_headphones_hyperdeck_mute
        - switch.office_headphones_mac_mute
        - switch.office_headphones_pc_mute
        - switch.office_speakers_chromecast_mute
        - switch.office_speakers_hyperdeck_mute
        - switch.office_speakers_mac_mute
        - switch.office_speakers_pc_mute
        - switch.office_webcam_monitor
        - switch.unused_plug
    local_status:
      topic: "homeassistant/status"
    remote_status:
      topic: "homeassistant-bitfocus-companion/status"
      # - base_topic: homeassistant-dashboard
      #   publish_attributes: true
      #   publish_timestamps: false
      #   publish_discovery: true
      #   include:
      #     entities:
      #       - entity_a
      #       - entity_b
      #   local_status:
      #     topic: "homeassistant/status"
      #   remote_status:
      #     topic: "homeassistant-dashboard/status"

################################################
## Template
################################################
template:
  - binary_sensor:
      - unique_id: a3b4c5d6-e7f8-4901-a234-567890123456
        name: Office Lights 25% Enabled
        default_entity_id: binary_sensor.office_lights_25_percent
        state: "{{ is_state_attr('light.office_lights', 'brightness', 64) }}"
      - unique_id: b4c5d6e7-f8a9-4012-b345-678901234567
        name: Office Lights 50% Enabled
        default_entity_id: binary_sensor.office_lights_50_percent
        state: "{{ is_state_attr('light.office_lights', 'brightness', 128) }}"
      - unique_id: c5d6e7f8-a9b0-4123-c456-789012345678
        name: Office Lights 75% Enabled
        default_entity_id: binary_sensor.office_lights_75_percent
        state: "{{ is_state_attr('light.office_lights', 'brightness', 191) }}"
      - unique_id: d6e7f8a9-b0c1-4234-d567-890123456789
        name: Office Lights 100% Enabled
        default_entity_id: binary_sensor.office_lights_100_percent
        state: "{{ is_state_attr('light.office_lights', 'brightness', 255) }}"
      - unique_id: e7f8a9b0-c1d2-4345-e678-901234567890
        name: Office Fan is Off
        default_entity_id: binary_sensor.office_fan_is_off
        state: "{{ is_state('fan.office_fan', 'off') }}"
      - unique_id: f8a9b0c1-d2e3-4456-f789-012345678901
        name: Office Fan Set to Slow
        default_entity_id: binary_sensor.office_fan_slow
        state: >
          {{ is_state('fan.office_fan', 'on')
            and state_attr('fan.office_fan', 'percentage') > 0
            and state_attr('fan.office_fan', 'percentage') <= 52 }}
      - unique_id: a9b0c1d2-e3f4-4567-a890-123456789012
        name: Office Fan Set to Medium
        default_entity_id: binary_sensor.office_fan_medium
        state: >
          {{ is_state('fan.office_fan', 'on')
            and state_attr('fan.office_fan', 'percentage') > 52
            and state_attr('fan.office_fan', 'percentage') <= 81 }}
      - unique_id: b0c1d2e3-f4a5-4678-b901-234567890123
        name: Office Fan Set to High
        default_entity_id: binary_sensor.office_fan_high
        state: >
          {{ is_state('fan.office_fan', 'on')
            and state_attr('fan.office_fan', 'percentage') > 81 }}
  - light:
      - unique_id: b0ef72e2-eea5-4e16-b71f-793371b1d564
        name: Office Video Lights
        default_entity_id: light.office_video_lights
        state: >-
          {{ is_state_attr('light.center_key_light', 'brightness', 51)
            and is_state_attr('light.center_key_light', 'color_temp', 143)
            and is_state_attr('light.left_key_light', 'brightness', 38)
            and is_state_attr('light.center_key_light', 'color_temp', 143)
            and is_state_attr('light.office_backlighting', 'brightness', 255)
            and is_state_attr('light.office_backlighting', 'color_temp', 156)
            and is_state('light.office_lights', 'off')
          }}
        turn_on:
          - action: light.turn_on
            target:
              entity_id: light.center_key_light
            data:
              color_temp: 143
              brightness: 51
          - action: light.turn_on
            target:
              entity_id: light.left_key_light
            data:
              color_temp: 143
              brightness: 38
          - action: light.turn_on
            target:
              entity_id: light.office_backlighting
            data:
              color_temp: 156
              brightness: 255
          - action: light.turn_off
            target:
              entity_id: light.office_lights
        turn_off:
          - action: light.turn_off
            target:
              entity_id: light.center_key_light
          - action: light.turn_off
            target:
              entity_id: light.left_key_light
          - action: light.turn_off
            target:
              entity_id: light.office_backlighting

################################################
## Input Boolean
################################################
input_boolean:
  sentinal_headset_enabled:
    name: Sentinal Headset Enabled
    icon: mdi:headset

################################################
## Light
################################################
light:
  - platform: switch
    name: Office Closet Lights
    entity_id: switch.office_closet_lights

################################################
## Script
################################################
script:
  set_office_lights_25_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_25_percent
                state: 'on'
            sequence:
              - action: light.turn_off
                entity_id: light.office_lights
        default:
          - action: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 25
              transition: 2

  set_office_lights_50_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_50_percent
                state: 'on'
            sequence:
              - action: light.turn_off
                entity_id: light.office_lights
        default:
          - action: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 50
              transition: 2

  set_office_lights_75_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_75_percent
                state: 'on'
            sequence:
              - action: light.turn_off
                entity_id: light.office_lights
        default:
          - action: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 75
              transition: 2

  set_office_lights_100_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_100_percent
                state: 'on'
            sequence:
              - action: light.turn_off
                entity_id: light.office_lights
        default:
          - action: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 100
              transition: 2

  set_office_fan_off:
    sequence:
      - action: fan.turn_off
        target:
          entity_id: fan.office_fan

  set_office_fan_slow:
    sequence:
      - action: fan.set_percentage
        target:
          entity_id: fan.office_fan
        data:
          percentage: 33

  set_office_fan_medium:
    sequence:
      - action: fan.set_percentage
        target:
          entity_id: fan.office_fan
        data:
          percentage: 66

  set_office_fan_high:
    sequence:
      - action: fan.set_percentage
        target:
          entity_id: fan.office_fan
        data:
          percentage: 99

################################################
## Automation
################################################
automation:
  - id: 0c527fe1-216b-4ace-8e81-004fe00484b9
    alias: Toggle Sentinal Headset
    description: >-
      Switches Sentinal to route voice communication audio over to theJabra Headset
      or the Ceiling Speakers
    mode: single
    triggers:
      - trigger: state
        entity_id: input_boolean.sentinal_headset_enabled
    actions:
      - action: switch.turn_on
        target:
          entity_id: >
            {% if trigger.to_state.state == 'on' %}
              switch.sentinal_enable_headset
            {% else %}
              switch.sentinal_enable_speakers
            {% endif %}

  - id: '1649041295671'
    alias: Control Office Closet Lights by Door Sensor
    description: When the Office Closet Door opens, turn on the light; when closed, turn it off.
    triggers:
      - trigger: state
        entity_id: binary_sensor.office_closet_door
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'on'
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.office_closet_lights
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'off'
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.office_closet_lights
        default: []
    mode: single

  - id: c6888d4f-2471-450d-a8ee-66a68c388169
    alias: Office Lights Scene Controls
    description: Utilizes a blueprint to map track lighting states on the Scene Controller in the Office.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - 391bbdf1c04fbdef1ba596217111f64d
        button_b2:
          - action: script.turn_off_lights_in_areas
            data:
              areas:
                - office

  - id: 1050b406-8102-486e-89b7-30f29fb39f35
    alias: Control Office Lights by Occupancy Sensor
    description: >
      When the Office is Occupied, turn on the backlighting.
      When the Office is Unoccopied, turn all lights off.
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.office_lights_occupancy
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_occupancy
                state: 'off'
            sequence:
              - delay:
                  minutes: 2
              - action: script.turn_off_lights_in_areas
                data:
                  areas:
                    - office
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.office_streamdecks
              - action: switch.turn_off
                target:
                  entity_id: switch.office_thinksmart_display_screen
        default:
          sequence:
            - if:
                - condition: numeric_state
                  entity_id:
                    - sensor.office_illuminance
                  below: 10
                - condition: state
                  entity_id: light.office_video_lights
                  state: 'off'
              then:
                - action: light.turn_on
                  target:
                    entity_id: light.office_lights
            - action: light.turn_on
              target:
                entity_id: light.office_backlighting
            - action: input_boolean.turn_on
              target:
                entity_id: input_boolean.office_streamdecks
            - action: switch.turn_on
              target:
                entity_id: switch.office_thinksmart_display_screen
    mode: restart
