###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/11/2018
#  @package      :  Presence
#  @description  :  Manages presence detection using a combination of motion
#                   and door/window sensors.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'presence'

    ################################################
    ## Zone
    ################################################
    zone.home:
      <<: *customize

    zone.work:
      <<: *customize

################################################
## Zone
################################################
zone:
  - name: Home
    latitude: !secret homeassistant.latitude
    longitude: !secret homeassistant.longitude
    radius: 12

  - name: Work
    latitude: !secret zone.work.latitude
    longitude: !secret zone.work.longitude
    radius: 250

################################################
## Map
################################################
map:
