###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  02/07/2023
#  @package      :  Stairway
#  @description  :  Manages lighting in the Stairway
###############################################################################
---
################################################
## Light
################################################
light:
  - platform: group
    name: Stairway Lights
    unique_id: 25bb040a-ae44-412d-9f6e-4ecbd1cc7816
    entities:
      - light.stairway_lights_switch
      - light.stairway_lights_aux_switch

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      downstairs_lights_on:
        friendly_name: Downstairs Lights On
        value_template: >
          {{
            is_state('light.stairway_lights', 'on')
            and is_state('light.downstairs_hallway_lights', 'on')
          }}
      downstairs_lights_off:
        friendly_name: Downstairs Lights Off
        value_template: >
          {{
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('downstairs_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('downstairs_hallway'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('garage'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('guest_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('gym'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            == 0
          }}
      upstairs_lights_on:
        friendly_name: Upstairs Lights On
        value_template: >
          {{
            is_state('light.hallway_lights', 'on')
            and is_state('light.kitchen_cabinet_lights', 'on')
          }}
      upstairs_lights_off:
        friendly_name: Upstairs Lights Off
        value_template: >
          {{
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('hallway'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('hallway_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('living_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('kitchen'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('dining_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('master_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('master_bedroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('office'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            == 0
          }}

################################################
## Automations
################################################
automation:
  - id: '1644120951513'
    alias: Stairway Scene Controller
    description: 'Utilizes a blueprint to control scenes on the stairway.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controls.yaml
      input:
        zooz_switch:
          - c27cdc188591fc457df3efb38b698aa2
          - cba4ca73f091aa4a74a4e5faae5395d9
        scene_1:
          - action: light.turn_on
            target:
              entity_id:
                - light.hallway_lights
                - light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
        scene_2:
          - action: light.turn_on
            target:
              entity_id:
                - light.downstairs_hallway_lights
                - light.stairway_lights
        scene_3:
          - action: light.turn_off
            target:
              area_id:
                - hallway
                - hallway_bathroom
                - living_room
                - kitchen
                - dining_room
                - master_bathroom
                - master_bedroom
                - office
        scene_4:
          - action: light.turn_off
            target:
              area_id:
                - downstairs_bathroom
                - downstairs_hallway
                - garage
                - guest_room
                - gym

  - id: 'f248725a-26e6-46f7-becd-bc53ccc662ef'
    alias: Stairway Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller on the Stairway.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch:
          - c27cdc188591fc457df3efb38b698aa2
          - cba4ca73f091aa4a74a4e5faae5395d9
        small_1_button_light: binary_sensor.upstairs_lights_on
        small_2_button_light: binary_sensor.downstairs_lights_on
        small_3_button_light: binary_sensor.upstairs_lights_off
        small_4_button_light: binary_sensor.downstairs_lights_off
