###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/05/2022
#  @package      :  Tablets
#  @description  :  Controls Kiosk Tablets.
###############################################################################
---
automation:
  - id: f126138c-bb79-4a9c-957a-a727ab53f95f
    alias: Restart Fully Kiosk Browsers
    description: Restart all tablets once a day to make sure that they don't get stuck.
    triggers:
      - trigger: time
        at: '03:00:00'
    actions:
      - action: button.press
        target:
          entity_id: |
            {{
              expand(integration_entities('fully_kiosk'))
              | selectattr('entity_id', 'search', '_restart_browser')
              | map(attribute='entity_id')
              | list
            }}
    mode: single
