###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  03/02/2019
#  @package      :  Weather
#  @description  :  Creates weather related entities
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

    ################################################
    ## Sensor
    ################################################
    sensor.exterior_temperature:
      <<: *customize
    sensor.exterior_humidity:
      <<: *customize

################################################
## Template
################################################
template:
  - sensor:
      - unique_id: a7b8c9d0-e1f2-4345-a678-901234567890
        default_entity_id: sensor.exterior_temperature
        state: "{{ state_attr('weather.pirateweather', 'temperature') | round(1, default=0) }}"
        device_class: temperature
        unit_of_measurement: "°F"
      - unique_id: b8c9d0e1-f2a3-4456-b789-012345678901
        default_entity_id: sensor.exterior_humidity
        state: "{{ state_attr('weather.pirateweather', 'humidity') | round(1, default=0) }}"
        device_class: humidity
        unit_of_measurement: "%"

automation:
  - id: '1702712886222'
    alias: Update ePaper Weather Displays
    description: Display external weather on the epaper displays by the exterior doors
    triggers:
      - trigger: time_pattern
        minutes: /15
    conditions:
      - condition: time
        after: "07:00:00"
        before: "02:00:00"
    actions:
      - data:
          background: white
          rotate: 0
          ttl: 300
          dither: false
          payload:
            - type: icon
              value: >
                weather- {%- set condition = states('weather.pirateweather') -%} {%-
                if condition == 'partlycloudy' -%}
                  {%- set condition = 'partly-cloudy' -%}
                {%- endif -%} {%- if condition == 'clear-night' -%}
                  {%- set condition = 'night' -%}
                {%- endif -%} {%- if states('sun.sun') == 'below_horizon' -%}
                  {%- if condition == 'sunny' -%}
                    night
                  {%- elif condition == 'partly-cloudy' -%}
                    night-partly-cloudy
                  {%- else -%}
                    {{ condition }}
                  {%- endif -%}
                {%- else -%}
                  {{ condition }}
                {%- endif -%}
              x: 42
              y: 5
              size: 75
              color: black
            - type: text
              value: "{{ states('sensor.weather_station_outdoor_temperature') | round }}°F"
              font: ppb.ttf
              x: 76
              y: 105
              size: 60
              color: red
              anchor: mm
            - type: text
              value: "Updated: {{ now().strftime('%I:%M %p') }}"
              font: ppb.ttf
              x: 76
              y: 135
              size: 15
              color: black
              anchor: mt
        target:
          device_id:
            - 93185d71c897d23075b33b802ad98658
        action: open_epaper_link.drawcustom
    mode: restart
