###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  03/02/2019
#  @package      :  Weather
#  @description  :  Creates weather related entities
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

    ################################################
    ## Sensor
    ################################################
    sensor.exterior_temperature:
      <<: *customize
    sensor.exterior_humidity:
      <<: *customize

weather:
  - platform: darksky
    api_key: !secret weather.darksky.api_key
    mode: daily

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:

      exterior_temperature:
        value_template: "{{state_attr('weather.dark_sky', 'temperature') | round(1)}}"
        device_class: temperature
        unit_of_measurement: "°F"

      exterior_humidity:
        value_template: "{{state_attr('weather.dark_sky', 'humidity') | round(1)}}"
        device_class: humidity
        unit_of_measurement: "%"
